export const API_URL = {
  BASE_URL: 'http://localhost:8080/api/v1/',
  CATEGORIES: 'categories',
  GETCATEGORIES: 'categories/all',
  SERVICES: 'services',
  GETSERVICES: 'services/all',
  WORKS: 'my-works',
  GETMYWORKS: 'my-works/all',
  BOOKINGS: 'bookings',
  CREATEBOOKINGREVIEW: 'bookings/create-review',
  BOOKING_REVIEWS: 'bookings/booking-reviews',
  UPDATEBOOKINGSTATUS: 'bookings/update-status',
  CLIENTBOOKINS: 'bookings/client-bookings',
  VERIFYBOOKINGOTP: 'bookings/verify-booking',
};
