export const API_URL = {
  // BASEURL: 'http://localhost:3000',
  BASEURL: 'https://glow-by-rishi-api.onrender.com',
  CATEGORIES: 'categories',
  GETCATEGORIES: 'categories/all',
  SERVICES: 'services',
  GETSERVICES: 'services/all',
  WORKS: 'my-works',
  GETMYWORKS: 'my-works/all',
  BOOKINGS: 'bookings',
  CREATEBOOKING: 'bookings/create',
  CREATEBOOKINGREVIEW: 'bookings/create-review',
  BOOKING_REVIEWS: 'bookings/booking-reviews',
  UPDATEBOOKINGSTATUS: 'bookings/update-status',
  CLIENTBOOKINS: 'bookings/client-bookings',
  VERIFYBOOKINGOTP: 'bookings/verify-booking',
  RESENDOTP: 'bookings/resend-otp',
};
